name: Cron job

on:
  schedule:
    - cron: '50 23 * * *'
    - cron: '59 23 * * 0'
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Daily Cron Job
        if: github.event.schedule == '50 23 * * *'
        run: node cron/dailyCron.js

      - name: Run Weekly Cron Job
        if: github.event.schedule == '59 23 * * 0'
        run: node cron/weeklyCron.js

      - name: Run Monthly Cron Job
        if: github.event.schedule == '0 0 1 * *'
        run: node cron/monthlyCron.js
