name: Cron job

on:
  schedule:
    - cron: '50 23 * * *'
    - cron: '54 23 * * 0'
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Cron Job
        run: |
          if [ "${{ github.event.schedule }}" == '50 23 * * *' ]; then
            node cron/dailyCron.js
          elif [ "${{ github.event.schedule }}" == '54 23 * * 0' ]; then
            node cron/weeklyCron.js
          elif [ "${{ github.event.schedule }}" == '0 0 1 * *' ]; then
            node cron/monthlyCron.js
          fi
