name: Cron job

on:
  schedule:
    - cron: '30 23 * * *'
    - cron: '31 23 * * 0'
    - cron: '0 0 1 * *'
    - cron: '45 7 * * *'
    - cron: '*/5 * * * *'

jobs:
  run-cron:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Set WITA timezone
        run: sudo timedatectl set-timezone Asia/Makassar
        
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Daily Cron
        if: |
          runner.os == 'Linux' &&
          github.event_name == 'schedule' &&
          github.event.schedule == '30 23 * * *'
        run: node cron/dailyCron.js

      - name: Run Weekly Cron
        if: |
          runner.os == 'Linux' &&
          github.event_name == 'schedule' &&
          github.event.schedule == '31 23 * * 0'
        run: node cron/weeklyCron.js

      - name: Run Monthly Cron
        if: |
          runner.os == 'Linux' &&
          github.event_name == 'schedule' &&
          github.event.schedule == '0 0 1 * *'
        run: node cron/monthlyCron.js

      - name: Run Test Cron
        if: |
          runner.os == 'Linux' &&
          github.event_name == 'schedule' &&
          github.event.schedule == '45 7 * * *'
        run: echo "Berjalan"

      - name: Run every 5th minute
        if: |
          runner.os == 'Linux' &&
          github.event_name == 'schedule' &&
          github.event.schedule == '*/5 * * * *'
        run: "echo 'Current Time : $(date)'"
